### ISSUE TITLE
Preferred event for lazy loading bigfile.nvim with Lazy.nvim

### ISSUE THREAD

**Issue by HaleTom** [LunarVim/bigfile.nvim#22]
For non-LunarVim users of Lazy.nvim, what is the preferred `event =` on which to load this plugin?

[Here](https://github.com/LunarVim/LunarVim/blob/4ffa7c455b5cc5d40efd8cbf1c3d91778741f490/lua/lvim/plugins.lua#L357) I see:

    event = { "FileReadPre", "BufReadPre", "User FileOpened" },

What is `"User FileOpened"`?  I searched but... no findey.

**Comment by LostInTheLogs** [comment]
It's best not to lazy load the plugin. the only thing it does on startup is create an BufReadPre autocmd
